---
title: "Actividad 6"
author: "Matías Martínez"
date: "12 de abril de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



####Ejercicio 2

```{r,echo=FALSE}
library(tidyverse)
```

1. 
```{r}
nrow(filter(mpg,year==2008 & hwy>31))

```

2.
```{r}
nrow(filter(mpg,cty==9 | hwy>90))
```

3.
```{r}
select(mpg,displ,hwy)
```

4.
```{r}
select(mpg,trans:hwy)
```

5.
```{r}
mutate(mpg,lxkm=hwy*(3.78541/1.60934))
```



####Ejercicio 3


```{r,echo =TRUE}
library("productplots")
str(happy)
```

1.

```{r,echo=TRUE}
filter(happy,!is.na(happy)) %>% group_by(sex,happy,year) %>% summarise(cont=n()) %>%arrange(year) %>% group_by(year,sex) %>% mutate(porcent=(cont/sum(cont)*100))
```

2.
```{r,echo=TRUE}

filter(happy,!is.na(happy)) %>% group_by(sex,happy,year) %>% summarise(cont=n()) %>% arrange(year) %>% group_by(year,sex) %>% mutate( porcent=(cont/sum(cont)*100)) %>% 
  ggplot(aes( x=year, y=porcent, colour=happy))+geom_point() + geom_smooth( method = 'loess') + labs(x="Año",y="Porcentaje",title="Gráfico de dispersión: Niveles de felicidad desde 1972 a 2006") +
  facet_wrap(~sex) + theme_bw(base_size = 12) + theme(plot.title = element_text(hjust = 0.5,colour="slateblue4",size=14,face="plain")) + guides(fill=guide_legend(title="Felicidad")) + scale_fill_manual(values=c("firebrick3","seagreen3","royalblue4"))
```

3.

Se denotan tendencias similares y estables en el tiempo para ambos géneros, no obstante, las mujeres gozan de proporciones más altas para los niveles de "muy feliz"" y "bastante feliz". 

4.
```{r,echo=TRUE}

filter(happy,!is.na(happy)) %>% group_by(sex,happy,age) %>% summarise(cont=n()) %>%arrange(age) %>% group_by(age,sex) %>% mutate(porcent=(cont/sum(cont)*100))  %>% 
  ggplot(aes(x=age,y=porcent,fill=happy))+geom_area() + labs(x="Edad",y="Porcentaje",title= "Gráfico de dispersión: Niveles de felicidad según edad") + 
  facet_wrap(~sex) + theme_bw() + scale_fill_manual(values=c("slategray2","cyan3","royalblue4"))+guides(fill=guide_legend(title="Felicidad")) + guides(fill=guide_legend(title="Felicidad")) +
  theme(plot.title = element_text(hjust = 0.5,colour="darkslategray",size=14,face="plain"))
```

5.

Se podría considerar el uso de mosaicos.
```{r,echo=FALSE}
library(ggmosaic)
```

```{r,echo=TRUE}


happy %>% filter(!is.na(happy)) %>% group_by(happy,marital) %>% arrange(marital)%>% group_by(marital,happy) %>% summarise(cont=n()) %>%
     ggplot() + geom_mosaic(aes(weight=cont,x=product(happy,marital),colour=happy,fill=happy),na.rm=TRUE,) + labs( x="Estado civil", y="Porcentaje",title="Gráfico de mosaicos: Porcentaje niveles de felicidad según estado civil") +
  theme_minimal(base_size=11) + guides(fill=guide_legend(title = "Felicidad", reverse = TRUE)) + scale_x_productlist(labels=labels) + coord_flip() + theme(plot.title = element_text(hjust = 0.5,colour="darkslategrey",size=13.7,face="plain")) + guides(fill=guide_legend(title="Felicidad")) + scale_fill_manual(values=c("firebrick3","seagreen3","royalblue4"))
```


```{r,echo=TRUE}
happy %>% filter(!is.na(happy)) %>% group_by(happy,finrela) %>%  arrange(finrela)%>% group_by(finrela,happy) %>% summarise(cont=n()) %>% 
  ggplot() + geom_mosaic(aes( weight=cont,x =product(happy,finrela), colour=happy, fill=happy))+ labs( x="Situación Financiera", y="Porcentaje",title="Gráfico de mosaicos: Niveles de felicidad según condición financiera") + 
  theme_minimal() + scale_x_productlist(labels=labels) + scale_fill_manual(values=c("firebrick3","seagreen3","royalblue4")) + coord_flip()+ guides(fill=guide_legend(title="Felicidad")) + guides(fill=guide_legend(title="Felicidad")) + theme(plot.title = element_text(hjust = 0.5,colour="darkslategrey",size=13.7,face="plain"))
```



6.

```{r,echo=TRUE}

happy %>% filter(!is.na(happy)) %>% group_by(happy,degree) %>%  arrange(degree)%>% group_by(degree,happy) %>% summarise(cont=n()) %>% 
  ggplot() + geom_mosaic(aes( weight=cont,x =product(happy,degree), colour=happy, fill=happy))+ labs( x="Escolaridad", y="Porcentaje",title="Gráfico de mosaicos: Niveles de felicidad según educación") + 
  theme_minimal() + scale_x_productlist(labels=labels) + scale_fill_manual(values=c("firebrick3","seagreen3","royalblue4")) + coord_flip() + guides(fill=guide_legend(title="Felicidad")) + theme(plot.title = element_text(hjust = 0.55,colour="grey20",size=14.2,face="plain"))
```

7.
```{r,echo=TRUE}

levels(happy$health)


happy %>% filter(!is.na(happy)) %>% group_by(happy,health) %>%  arrange(health) %>% group_by(health,happy) %>% summarise(cont=n()) %>%drop_na() %>% 
    ggplot() + geom_mosaic(aes( weight=cont, x=product(happy,health), colour=happy, fill=happy)) + labs( x="Salud", y="Porcentaje", title="Gráfico de mosaicos: Niveles de felicidad según salud") + scale_fill_manual(values=c("firebrick3","seagreen3","royalblue4")) + theme(plot.title = element_text(hjust = 0.4,colour="purple4",size=14.2,face="plain")) + guides(fill=guide_legend(title="Felicidad"))


```








